### PR TITLE
Add address sanitizer.

### PR DESCRIPTION
**Pull request by arjo129**
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

### Implemented feature

Adding address sanitizer as part of open-rmf/rmf#47 . 

### Implementation description

The structure is essentially the same as pr #20. Basically ASAN also has a colcon mixin and we can reuse the stuff from `ros-tooling`. The good news is that there are no memory leaks so far while running the tests.

### CODE REVIEW

**Comment by arjo129** [comment]
Usually, if there are errors ASAN will cry out very loudly on the `STDERR` interface and return non zero execution value thus triggering the :x: on the CI. One can check the log in the workflows tab for the exact details of the memory leak.

**Comment by gbiggs** [comment]
> Usually, if there are errors ASAN will cry out very loudly on the STDERR interface and return non zero execution value thus triggering the x on the CI.

How easy are those logs to find and access for offline reading?

> An alternative would be to use valgrind's memcheck which I don't believe has such limitations (although it has much more overhead),

Ideally we only want memory errors in our code or our usage of other APIs (e.g. ROS APIs). Valgrind is possibly easier to restrict to that than `msan`?

I think the overhead of `valgrind` is acceptable since we will likely only run this test once a day in the nightly build.

**Comment by arjo129** [comment]
> How easy are those logs to find and access for offline reading?

The [following instructions]() allow you to download the logs ``. To be honest, the moment asan detects *one* leak it will fail, so its a bit like python it that sense.

> Ideally we only want memory errors in our code or our usage of other APIs (e.g. ROS APIs). Valgrind is possibly easier to restrict to that than msan?

I don't know if we can restrict it. But atleast I don;t need to instrument *every* dependency like I do with `msan` (`msan` will give false positives otherwise).

**Comment by gbiggs** [comment]
Take a look at [this comment](https://github.com/open-rmf/rmf_traffic/pull/20#issuecomment-836443059) for a nice way to handle the colcon output.

**Review by gbiggs — APPROVED** [review]

**Pull request merged**
