### PR TITLE
Update the README

### PR DESCRIPTION
**Pull request by mxgrey**

### CODE REVIEW

**Comment by mxgrey** [comment]
Since `rmf_traffic` doesn't contain as much content as `rmf_core` used to, I think we should push the high level README content into the meta `rmf` repo and just link to that from `rmf_traffic`.

**Comment by mxgrey** [comment]
This resolves #9

**Review by gbiggs — APPROVED** [review]

**Comment by gbiggs** [comment]
I think that the correct place for the removed content would be the root page of the documentation in the `rmf_docs` repository. We can optionally add it to that repository's README as well, if we want, but I don't think that's necessary since the entry page for RMF should be the documentation site, not a GitHub repository.

**Comment by mxgrey** [comment]
All of the removed content is actually old junk that shouldn't even exist anymore, because it's incorrect (irredeemably out of date).

The most up to date high-level documentation is [here](https://osrf.github.io/ros2multirobotbook/) ([source](https://github.com/osrf/ros2multirobotbook)). I suppose we may want to migrate the information in that "book" into `rmf_docs` at some point.

**Pull request merged**
