### PR TITLE
alt has no time, but has cost, so update the time to cost

### PR DESCRIPTION
**Pull request by heyanwei**
If we define "RMF_TRAFFIC__AGV__PLANNING__DEBUG__PLANNER", it will show this problem.

```
DifferentialDrivePlanner.cpp:1372:71: error: ‘const struct rmf_traffic::agv::planning::Traversal::Alternative’ has no member named ‘time’
 1372 |       std::cout << "Cost " << approach_cost + entry_event_cost + alt->time
      |                                                                       ^~~~

```

### CODE REVIEW

**Comment by mxgrey** [comment]
Thanks for the PR!

I apologize for the inconvenience, but we have a [DCO](https://wiki.linuxfoundation.org/dco) requirement for contributions, to protect us from liability in case someone is trying to make contributions when they're not supposed to (e.g. the company they work for does not allow it). The DCO sign-off effectively says that you promise you're allowed to make the contribution.

To fix the DCO sign-off for your commit, please follow the instructions [here](https://github.com/open-rmf/rmf_traffic/pull/79/checks?check_run_id=6647462334) under the `Rebase the branch` section. Then I'll be happy to merge this PR :grin:

**Comment by heyanwei** [comment]
你的邮件我已收到，谢谢！

**Review by mxgrey — APPROVED** [review]
Thanks for this fix!

**Comment by heyanwei** [comment]
你的邮件我已收到，谢谢！

**Pull request merged**
